refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S.%3f)}] {h({l:<5})} [{T}] {M}:{L} - {m}{n}"
  requests:
    kind: rolling_file
    path: "log/manga_overlay.log"
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S.%3f)}] {h({l:<5})} [{T}] {M}:{L} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1mb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "log/manga_overlay.{}.log"

loggers:
  manga_overlay:
    level: debug
    appenders:
      - stdout
      - requests
    additive: false

root:
  level: info
  appenders:
    - stdout
    - requests