refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{h({l})} {d(%Y-%m-%d %H:%M:%S)} {f}:{L} - {m}{n}"
  requests:
    kind: file
    path: "log/egui_ocr.log"
    encoder:
      pattern: "{h({l})} {d(%Y-%m-%d %H:%M:%S)} {f}:{L} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
    - requests